version: "3.7"

services:
  fuel_locker:
    build:
      context: ./fuel-locker
      dockerfile: Dockerfile
    volumes:
      - "./fuel-locker:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
